### ISSUE TITLE
Zabbix sender, BME680 and bme680-zabbix_sender

### ISSUE THREAD

**Issue by williamdes** [rust-unofficial/awesome-rust#1136]
I just created my first Rust program and released it: https://github.com/williamdes/bme680-zabbix_sender

It uses two awesome crates:
- [zbx-sender-rs](https://github.com/ava57r/zbx-sender-rs) (a Zabbix sender program like the CLI binary found on Debian/Ubuntu https://linux.die.net/man/1/zabbix_sender)
- [bme680](https://github.com/marcelbuesing/bme680) (see [Bosch](https://www.bosch-sensortec.com/products/environmental-sensors/gas-sensors/bme680/) description of this sensor)

I am not sure in what section to put the 3 projects

**Comment by palfrey** [comment]
We've recently made a change to the rules regarding additions of new projects, and in order to attempt to be as fair as we can with the process we're now using external popularity metrics to guide this. Our current standards are a minimum of 50 stars on Github, 2000 downloads for projects with published crates or equivalent values in other areas (e.g. downloads in other places, star-type popularity in other repositories).

Your new project doesn't hit that threshold, but the two libraries do. The Zabbix library probably wants an `Observability` section under libraries (as per the one under Applications) and the sensor one can go under  `Embedded`. Thanks!

**Comment by williamdes** [comment]
Thanks for the feedback, I may do a PR but any newbie to the project can make this before me
Maybe you can tag this one as newbie or good first issue depending on what you have available

**Comment by palfrey** [comment]
Closing as there's no PR been made, and this is quite old
