### ISSUE TITLE
Suggestion: Add a "Last updated" date next to the project name

### ISSUE THREAD

**Issue by SSebigo** [rust-unofficial/awesome-rust#1158]
It would be quite useful to have the last updated date of each project listed next to their name. Maybe with Github Actions.

**Comment by palfrey** [comment]
This would be hard to do. Firstly, because we're already hitting rate limits on the github api given the list of projects to check. Secondly, most of the projects are on Github, but not all, so updating the non-Github projects would be a bunch of effort. Thirdly, it's not always a useful metric. Some projects haven't been updated for months because they're effectively complete, which isn't a bad thing.
