### ISSUE TITLE
Add rust-gomoku to Games

### ISSUE THREAD

**Issue by namkyu1999** [rust-unofficial/awesome-rust#1162]
Can rust-gomoku be added to the list of Games libraries?

Crate: https://crates.io/crates/rust-gomoku
Github: https://github.com/namkyu1999/rust-gomoku

thank you!

**Comment by palfrey** [comment]
We've recently made a change to the rules regarding additions of new projects, and in order to attempt to be as fair as we can with the process we're now using external popularity metrics to guide this. Our current standards are a minimum of 50 stars on Github, 2000 downloads for projects with published crates or equivalent values in other areas (e.g. downloads in other places, star-type popularity in other repositories).

Unfortunately the project you've suggested doesn't reach these thresholds. If you think that we've miscounted or there is another public metric that you think we should take into account, then please re-open this issue and detail where else we should be looking.
