### ISSUE TITLE
CI Build fails

### ISSUE THREAD

**Issue by TornaxO7** [rust-unofficial/awesome-rust#1621]
If you take a look into the different PRs their CI is failing due to `build.rs` and some network issue. Is there a solution to this?

**Comment by rxst** [comment]
Yes, we need to fix the parsing of request URLs. So for [PR](https://github.com/rust-unofficial/awesome-rust/actions/runs/7129052160/job/19432284067?pr=1614) some failed checks were because the URLs parsed wrong. They URLs like _https://api.github.com/repos/lucid-kv/lucid,_ so comma in end break URL.
But in most cases, we have 403 so we probably need a different user for checks.

![Screenshot 2023-12-14 at 14 00 41](https://github.com/rust-unofficial/awesome-rust/assets/28845934/5e89a385-145e-486c-b7f1-a8a1fc95c553)

**Comment by palfrey** [comment]
The 403s are mostly due to Github hitting rate limits because we chek. Repos are only checked once per week and in theory if the `main` branch was edited fairly recently then PRs should use the cached checks from that. `main` branch checks also have an actual user credential applied to them (which we can't use on PRs, or people would be able to abuse it).

https://github.com/rust-unofficial/awesome-rust/pull/1628 fixes all the current ones. PRs in the future to fix things before I get the time to look at them would be most appreciated!
