### ISSUE TITLE
Would like to add a couple of little projects but don't know if they're awesome or not.

### ISSUE THREAD

**Issue by aleshaleksey** [rust-unofficial/awesome-rust#537]
Hello Rustaceans of awesome-rust,

I would like to add a little application (or two) here, but I don't know whether they count as awesome or junk in the eyes of Rustiety. Both are in Rust and use Conrod for the ui.

The first is a dice roll success distribution generator (mostly for making homebrew table top games), so its of limited utility:
[AZDice](https://github.com/aleshaleksey/AZDice).

Also, I have a not quite finished flat RPG (it compiles but is likely to remain a work in progress for a while). Thus I don't know how appropriate it is to put it here.
[TGWM](https://github.com/aleshaleksey/TGWM).

All the best,
Alek

**Comment by webdesus** [comment]
I think better idea for `rust-unoffical` was create new repository `awesome-projects`, and add link in awesome-rust. Cuz this realy might be intresting projects, but i think many people wait from this list only lib things... maybe i wrong. 

P.S @aleshaleksey nice projects, can you add screenshots to your repository?

**Comment by aleshaleksey** [comment]
Well that's the thing, ```awesome-rust``` has a lot of genuinely useful lib-type crates which developers use as extensions to the language (I use them too). On the other hand it also has quite a few applications (each with its own uses). Thus if the given list contained only libs I would know not to post here, and if it contained only applications I would have fewer misgivings than I do.

As for whether or not these should be separate lists or whether it's good to have applications as examples of the use of Rust in the same list, well, that's probably another question.

@webdesus Thanks for the suggestion. I have now added screenshots. Perhaps this will make it easier to judge.

**Comment by luciusmagn** [comment]
@webdesus Yes, you are wrong, but it's no problem. Here, we keep not just awesome Rust libraries, but also applications, tools and learning materials. There was even a time when we had an icon theme in the list, but that was since removed since the link to Rust was too weak.

The point of this list being so monolithic is that we want to collect all awesome resources in one place, not split it across several repositories or even markdown pages. Of course, it has its trade-offs, but we have eventually decided that for us, the pros of a single huge list outweigh the cons.

@aleshaleksey Your projects look very nice. We host several WIP projects as they might still be very useful or provide educational value. I see nothing wrong with your work and I find especially AZDice to be interesting. I think it would be nice if the generator could be used from the command-line as well, but that's just a personal wish, since you asked for feedback. :)

I think that there's nothing preventing you from opening a PR to add the projects to the list. Just make sure to follow format and it will be fine.

Just a thing that piqued my interest, what WM are you using on your system? I don't think I have ever seen windows looking like this.

**Comment by aleshaleksey** [comment]
@luciusmagn 
i) I see. That clears things up somewhat. In that case I will open a PR. At best someone will find them useful, at worst, it will be good motivation for me  to make them better.
ii) As for the generator, it was originally cli, which generated the csv and displayed a sample of the probabilities (so now I've uploaded it). But it didn't do graphs, and since I would be opening them anyway, it seemed nice to be able to generate and view in one, hence the GUI version. Well, in any case I am glad for the feedback.
iii) WM: I think it may be an artefact of Github putting an extra line around the screenshots, but it's LXDE/Openbox (I do some stuff on a low power machine, and switching between different OSs (or even visual styles) throws me off).

Anyway I guess that I will close this issue since it is essentially solved.
Than you.
