### ISSUE TITLE
Would like to add library, not sure of category.

### ISSUE THREAD

**Issue by aleshaleksey** [rust-unofficial/awesome-rust#595]
Hello again,

I would like to add another project, which is an "education" related library ([libchmq](https://github.com/aleshaleksey/libchmq)). However, there is not an "education" category, so I would like to ask for advice as to how to proceed.

Thanks in advance,
Alek.

**Comment by swarnimarun** [comment]
I nice idea would be to add it to a miscellaneous section.
Cause this isn't really education, I mean it can change depending on the context. I believe people in the list would think education is related to Rust education.

**Comment by palfrey** [comment]
We've recently made a change to the rules regarding additions of new projects, and in order to attempt to be as fair as we can with the process we're now using external popularity metrics to guide this. Our current standards are a minimum of 50 stars on Github, 2000 downloads for projects with published crates or equivalent values in other areas (e.g. downloads in other places, star-type popularity in other repositories).

Unfortunately the project you've described here doesn't reach these thresholds. If you think that we've miscounted or there is another public metric that you think we should take into account, then please re-open this issue and detail where else we should be looking.
