### ISSUE TITLE
remove typemap from list

### ISSUE THREAD

**Issue by BurntSushi** [rust-unofficial/awesome-rust#627]
I'm not sure what the process is for removing crates from this list, but we should probably drop typemap since it doesn't compile on Rust stable and appears unmaintained. See: https://news.ycombinator.com/item?id=19297233

(As far as I can tell, most or all of @reem's crates are unmaintained, so we should stop suggesting them and stop depending on them. I think typemap is the only such crate on this list.)

**Comment by kud1ing** [comment]
We've had discussions some time ago. I prefer that the code we link is useful in the sense that it can be used and does something meaningful.

However if there is a gap in the Rust ecosystem i think it is useful to point to inital attempts either for inspiriration or for people to pick up the torch.

In this case, i don't know. Are there alternatives?

**Comment by BurntSushi** [comment]
This list is called "Awesome Rust." I feel like anything that is both unmaintained and won't compile on the latest stable version of Rust is definitively *not* "Awesome." I don't think it's relevant whether there's a gap in the ecosystem or whether there are alternatives.

But that's just me. If you want to change this from "Awesome Rust" to "Awesome Rust and not so Awesome Rust," then sure, maybe add a new section or something? I'm not sure. Seems weird to me though.

**Comment by kud1ing** [comment]
From the POV of users i agree 100% with the expectation that projects should compile.
Maintenance status is not always easy to decide in general, eg.g. for stable projects that were untouched for quite some time.

Developers willing to invest in the ecosystem OTOH might also be interested in currently unmaintained projects. In the meantime there is also now https://github.com/not-yet-awesome-rust/not-yet-awesome-rust so such projects could go there.

On a general note, i've semi-retired from this project quite some time ago but jumped in since some issues and PRs were unhandeld for some time.

**Comment by BurntSushi** [comment]
@kud1ing Thanks!

> Maintenance status is not always easy to decide in general, e.g. for stable projects that were untouched for quite some time.

Yeah, totally. Probably the best we can do is just let people file bugs when projects stop working and are clearly not maintained.
