### ISSUE TITLE
Remove those badges from README.md

### ISSUE THREAD

**Issue by qlcom** [rust-unofficial/awesome-rust#963]
they bloats up the markdown source

**Comment by qlcom** [comment]
https://github.com/rust-unofficial/awesome-rust/pull/964

**Comment by palfrey** [comment]
Short answer: no
Long answer: no, because they provide useful information. However it's plausible we may want to revisit the format and consider how to redo them, or maybe move to a data format of the list that we use to say generate versions with and without build badges or something. See existing discussion at #479

**Comment by qlcom** [comment]
> because they provide useful information

if someone is interested in a repository, they visit it and get more information there.

**Comment by qlcom** [comment]
instead of making a simple list, you are producing giant mess. don't do that.
